feat: Add delivery list view
ISPP-07/frontend-cyc pull request #44
Opened 2024-03-14 22:45 UTC by Ronald752

# Description

In this PR, the views corresponding to the food deliveries are being developed, which are the list, the delivery creation and the details of each delivery.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# Screenshot(If applies):
![image](https://github.com/ISPP-07/frontend-cyc/assets/73199700/e870c178-242a-4339-acb0-9d4c3c82eece)

2024-03-15 19:03 UTC, Ronald752 commented
At the moment my functionality is not complete, but advanced enough to request a review of what is already developed.
In the list of deliverables, a part of its details is missing.
Note that the date is not shown in the same format as the mockup, because I am waiting to know in which format it will be sent by the backend. 
Finally, I need to connect the delivery record so that it is created correctly.

2024-03-16 09:11 UTC, sebasruii requested changes
Great job Ronald! I really like your new designs. There is some styling that could use a little improvement:
![image](https://github.com/ISPP-07/frontend-cyc/assets/73228845/89179083-09ef-425c-86cf-ece978fe6f47)
The input fields should be aligned in their respective column. Overall great job, and Good use of MockAPI since backend is not ready yet. Check the reviews on these files:

2024-03-16 09:11 UTC, sebasruii commented on src/app/components/sidebar.jsx
When I press on `Añadir entregas`, the modal does not show up
![image](https://github.com/ISPP-07/frontend-cyc/assets/73228845/bbdae95c-011f-4bd0-a4d3-af34aa4886f1)

2024-03-16 09:11 UTC, sebasruii commented on src/app/deliveries/page.jsx
Also (maybe this is not related to your implementation), when the page is displayed in a narrow viewport, the + (button for creating a delivery) does not pop up the modal
![image](https://github.com/ISPP-07/frontend-cyc/assets/73228845/ef553cb9-9e72-4e5f-b64e-504e8a85d480)

However, it does pop up in a wide viewport (such as full screen)

2024-03-16 11:56 UTC, Ronald752 commented on src/app/deliveries/page.jsx
I just checked and you are right, however I noticed that in the family and inventory views, the create button does not work either when the screen is reduced in size. Possibly it has to do with some property of the search bar.

2024-03-16 13:37 UTC, Ronald752 commented on src/app/deliveries/page.jsx
I've tried to fix it by using a grip with three columns, but I'm having trouble sizing the buttons in the last column and there's a lot of white space.

I have managed to get them aligned by applying a slight offset.

However I have detected that when applying the scrolling, this causes that when changing the size of the screen, everything looks messy, but the current version is responsive.
Therefore I have preferred to remove the scrolling until I find a solution that does not affect the change of screen dimensions.

2024-03-16 13:40 UTC, Ronald752 commented on src/app/deliveries/page.jsx
Regarding the + button, I've fixed it, apparently they hadn't added the handleClick feature.

2024-03-16 14:49 UTC, Ronald752 commented on src/app/deliveries/page.jsx
I have already made the change to icons, I hope you like it.

2024-03-16 14:51 UTC, Ronald752 commented on src/app/components/sidebar.jsx
I have checked which performs the redirect to the view, I think the error is due to not passing the modal status correctly, also I noticed that when you open the modal, there is no specific url, it may vary depending on the background. 
This error happens with all the other view creation buttons.

2024-03-16 15:16 UTC, Ronald752 commented
At the moment I have added the functionality that when the status of a delivery is changed, a PUT request is made.

2024-03-28 09:41 UTC, sebasruii requested changes
Nice changes, please resolve conflicts and take into account the following changes:

2024-03-28 09:41 UTC, sebasruii commented on src/app/components/DeliveriesForm.jsx
Add a `event.preventDefault()` inside the form submit handler (pass event as a parameter) to avoid this 
![image](https://github.com/ISPP-07/frontend-cyc/assets/73228845/fcd11e65-12d0-4135-9963-836509f50ac5)

2024-03-28 09:41 UTC, sebasruii commented on src/app/components/DeliveriesForm.jsx
Please, remember to remove the console.log()
![image](https://github.com/ISPP-07/frontend-cyc/assets/73228845/e68bf682-455a-4cac-acea-b84eb7ae8b49)

2024-03-28 09:42 UTC, sebasruii commented on src/app/components/DeliveriesForm.jsx
(Just remove the ones you use for this feature)

2024-03-29 18:06 UTC, sebasruii commented
It is also necessary that the update method is connected to the backend and not MockAPI 
![image](https://github.com/ISPP-07/frontend-cyc/assets/73228845/533bf77a-259e-4010-916b-950708845e06)
The edit view is not currently implement, only the update of delivery status

2024-03-30 02:15 UTC, Ronald752 commented
I have made the changes you requested, I have implemented the functionality that allows you to change the status of a delivery. I also modified the buttons to keep the styles of the other views, however the edit button does nothing at the moment.

2024-03-30 13:01 UTC, sebasruii approved these changes
Great job Ronald 👍🏻

2024-03-30 13:03 UTC, merged