Feature/43 filter and search
ISPP-07/frontend-cyc pull request #92
Opened 2024-04-07 15:48 UTC by Ronald752

# Description

Search and filtering options for the main list views have been added in this PR.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-04-07 15:55 UTC, Ronald752 commented
In the family view:
1. You can search by family name.
In the inventory view:
1.You can search by product name and by quantity.
2. You can filter by expiry dates.
In the deliveries view:
You can search by family name and by delivery status. 2.
2. You can filter by delivery dates.

2024-04-18 23:05 UTC, Ronald752 commented
I have added a button that implements a filter in the following views:
1. Family view:
- Clicking the button will show all those families that are due for renewal soon, or in your case the renewal date has already expired.
2. Food view:
 By clicking on the button, all products with an expiry date within the next 30 days will be displayed.

2024-04-19 15:37 UTC, AntonioRodriguezRuiz commented
Could you add a filter to products by warehouse?

2024-04-19 15:39 UTC, AntonioRodriguezRuiz requested changes

2024-04-19 15:39 UTC, AntonioRodriguezRuiz commented on src/app/deliveries/page.jsx
> +			setFilteredData(filtered)
It would be nice if it also filtered by product name. For example if I type "arroz" it gives me deliveries with products containing that string

2024-04-20 14:55 UTC, AntonioRodriguezRuiz approved these changes
Good job

2024-04-20 14:55 UTC, merged